# Generated by Django 4.1.7 on 2023-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estaVivo',
            field=models.BooleanField(default=True),
        ),
    ]
